<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>0.7.0</Version>
    <Authors>Eddie Velasquez</Authors>
    <Product>Bach Music Library</Product>
    <Copyright>Copyright (c) 2012-2023, Eddie Velasquez</Copyright>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageProjectUrl />
    <RepositoryUrl>https://github.com/eddievelasquez/bach</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <LangVersion>latest</LangVersion>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Bach.Model.Library.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <None Update="Bach.Model.ExternalAnnotations.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>